### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Nicklastoft** [Krealle/Cell_UnitFrames#73] opened 2024-09-14 22:38 UTC
### Addon Version

1.3.3

### World of Warcraft Version

Retail

### Describe the bug

Player Mana bar as Balance druid is stuck around 40% when in nostance or moonkin form (aka, when i have secondary power)

### Steps to reproduce

Step 1: Roll of a druid
Step 2: Go balance
Step 3: Rethink steps 1 and 2
Step 4: look at mana bar for player while not in a form, or in moonkin form

**Comment by Krealle** [comment] 2024-09-15 10:41
Closing since technically not a bug, will be resolved with #26

**Closed by Krealle** 2024-09-15 10:41 UTC
Labels: bug
