### ISSUE TITLE
[Bug] Mana Oils not showing

### ISSUE THREAD

**Issue by zandadoum** [Krealle/Cell_UnitFrames#134] opened 2024-10-16 15:15 UTC
### Addon Version

1.4

### World of Warcraft Version

Retail

### Describe the bug

I enabled all buff and debuff options, i dont use white/blacklist
i might be doing something wrong, but all my buffs and debuffs show up properly, except the Algari Mana Oil I put on my weapon.

it shows on the default blizzard buff list, but not in the buff list on cell unit frames

### Steps to reproduce

use an Algari Mana Oil on your weapon: buff doesn't show anywhere

**Comment by Krealle** [comment] 2024-10-17 17:25
You aren't doing anything wrong, temporary weapon enchants simply aren't considered as Auras, and therefor won't show up.
Since it's technically not a bug, I'll be closing this issue, but feel free to open another to add this as a feature.

**Closed by Krealle** 2024-10-17 17:25 UTC
Labels: bug
